/**
 * Spend Track UI
 * User interface to visualize monthy spendings
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: roy_khoury12@hotmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CategoryMapping { 
    description?: string;
    category?: string;
}

